export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=
export ATLAS_TOKEN=

export GCP_ACCOUNT_FILE=
export GCP_CLIENT_SECRET=

export SSH_KEY_FILE=
export AZURE_PUBLISH_SETTINGS=
export AZURE_SUBSCRIPTION_NAME=