#!/usr/bin/env bash

# /etc/init.d/salt-bootstrap
# description: salt-bootstrap daemon
# processname: salt-bootstrap

# chkconfig: 345 80 30
# description: salt-bootstrap daemon
# processname: salt-bootstrap

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


NAME=`basename $0`
LOG_DIR="/var/log/saltboot.log"
SALTBOOT_PORT=7070

get_pid() {
    ps -o pid= -C $NAME
}

is_running() {
    [ -n "$(ps -o pid= -C $NAME)" ]
}

case "$1" in
    start)
    mkdir -p $LOG_DIR
    if is_running; then
        echo "Already started"
    else
        echo "Starting ${NAME}"
        SALTBOOT_PORT=$SALTBOOT_PORT /usr/sbin/salt-bootstrap &
    fi
    ;;
    stop)
    if is_running; then
        echo -n "Stopping ${NAME}.."
        kill `get_pid`
        for i in {1..10}
        do
            if ! is_running; then
                break
            fi
            echo -n "."
            sleep 1
        done
        echo
        if is_running; then
            echo "Not stopped; may still be shutting down or shutdown may have failed"
            exit 1
        else
            echo "Stopped"
        fi
    else
        echo "Not running"
    fi
    ;;
    restart)
    $0 stop
    if is_running; then
        echo "Unable to stop, will not attempt to start"
        exit 1
    fi
    $0 start
    ;;
    status)
    if is_running; then
        echo "Running"
    else
        echo "Stopped"
        exit 1
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
