#!/bin/bash

# Generates a manifest file for Docker images that would have been generated by Packer in case of public cloud images

set -ex -o pipefail

: ${DOCKER_REPOSITORY?}
: ${IMAGE_UUID?}
: ${DOCKER_IMAGE_NAME?}
: ${TAG?}
: ${IMAGE_NAME?}
: ${OS?}
: ${OS_TYPE?}

MANIFEST=/tmp/manifest.json
echo "{}" > $MANIFEST

add_arg_to_manifest() {
  echo $1 $2
  echo "$(jq --arg key "$1" --arg value "$2" '.[$key] = $value' $MANIFEST)" > $MANIFEST
}

add_argjson_to_manifest() {
  echo $1 $2
  echo "$(jq --arg key "$1" --argjson value "$2" '.[$key] = $value' $MANIFEST)" > $MANIFEST
}

add_arg_to_manifest "uuid" "$IMAGE_UUID"
CREATED=$(echo "${IMAGE_NAME}" | grep -o "[0-9]\+" | head -1)
add_argjson_to_manifest "created_at" "$CREATED"
add_arg_to_manifest "os" "$OS"
add_arg_to_manifest "os_type" "$OS_TYPE"
add_arg_to_manifest "image_name" "$IMAGE_NAME"
add_arg_to_manifest "description" "Yarn ${TAG} image"
add_argjson_to_manifest "manifest" "{\"builds\": [{\"builder_type\": \"yarn\", \"artifact_id\": \"${DOCKER_REPOSITORY}/${DOCKER_IMAGE_NAME}\"}]}"
add_argjson_to_manifest "package_versions" "$(cat /tmp/package-versions.json)"
add_argjson_to_manifest "tags" "{}"
