---
- hosts: local
  tasks:
   - name: (B1) Install basic tool dependencies on Debian / Ubuntu
     package: name={{item}} state=installed
     with_items:
      - apt-utils
     when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

   - name: (B2) Install basic tools
     package: name={{item}} state=installed
     with_items:
      - file
      - sudo
      - curl
      - wget
      - tar

   - name: (B3) Install lsb tools on SLES / SUSE / Debian / Ubuntu
     package: name={{item}} state=installed
     with_items:
      - lsb-release
     when: (ansible_distribution == 'Suse' or ansible_distribution == 'SLES' or ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

   - name: (B3) Install basic tools
     package: name={{item}} state=installed
     with_items:
      - redhat-lsb
     when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

   - name: (B4) Install which expclitly on SLES 12
     package: name={{item}} state=installed
     with_items:
      # Suse12 doesn't come with 'which' by default.
      - which
     when: (ansible_distribution == 'Suse' or ansible_distribution == 'SLES') and ansible_distribution_major_version == '12'

   - name: (B5) Install tools needed for daemons
     package: name={{item}} state=installed
     with_items:
      - ntp
      - rsyslog
