---
- hosts: local
  tasks:
   - name: (D1) Install developer tools
     package: name={{item}} state=installed
     with_items:
      - less
      - vim

   - name: (D2) Install gcc on Debian / Ubuntu / Centos / RHEL
     package: name={{item}} state=installed
     with_items:
      - gcc
     when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

   - name: (D2) Install gcc - force on SLES on SLES 12
     # Using package / zypper doesn't work as force-resolution is not supported
     # Using --replacefiles as there are conflicts and we want to take control over.
     command: zypper --non-interactive --no-gpg-checks install --force-resolution --replacefiles gcc
     when: (ansible_distribution == 'Suse' or ansible_distribution == 'SLES') and ansible_distribution_major_version == '12'

   - name: (D2) Install gcc - Force on SLES on SLES 11
     # Using package / zypper doesn't work as force-resolution is not supported
     command: zypper --non-interactive --no-gpg-checks install --force-resolution gcc
     when: (ansible_distribution == 'Suse' or ansible_distribution == 'SLES') and ansible_distribution_major_version == '11'
