---
- hosts: local
  tasks:
   - name: (H0) Install tools needed for ambari
     package: name={{item}} state=installed
     with_items:
      # Extra stuff needed for ambari on debian7/ubuntu14
      - libffi-dev
      # This line is the output of 2 days of debugging. QE Ambari setup needs this to
      # start firefox, but doesn't install it. Debugging was hard as Run-tests job later
      # installs it erasing the evidence. This mysteriously works when openJDK7
      # is involved instead of OracleJDK8.
      - libasound2
      - libxrender1
      - libdbus-glib-1-2
      - libgtk2.0-0
      # Some oozie tests needs the 'column' command
      - bsdmainutils
     when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

   - name: (H1) Install python related stuff needed
     package: name={{item}} state=installed
     with_items:
      # Extra stuff needed for ambari on debian7/ubuntu14
      - python-dev
     when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

   - name: (H1) Install python related stuff needed
     package: name={{item}} state=installed
     with_items:
      # Extra stuff needed for ambari on Suse and Centos7
      - python-devel
     when: (ansible_distribution == 'Suse' or ansible_distribution == 'SLES' or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')

   - name: (H1) Install python related stuff needed
     package: name={{item}} state=installed
     with_items:
      - python-pip

   # Wire-encryption tests need this module
   - name: (H2) Wire-encryption dependencies
     command: pip install requests

   #- block:
   #  when: (ansible_distribution == 'Suse' or ansible_distribution == 'SLES') and ansible_distribution_major_version == '11' and ansible_distribution_release == '4'
