CLUSTERMANAGER_VERSION: {{ salt['environ.get']('CLUSTERMANAGER_VERSION', False) }}
CLUSTERMANAGER_BASEURL: {{ salt['environ.get']('CLUSTERMANAGER_BASEURL', False) }}
CLUSTERMANAGER_GPGKEY: {{ salt['environ.get']('CLUSTERMANAGER_GPGKEY', False) }}
