 - hosts: all
   pre_tasks:
     - name: Verify Ansible meets SCAP-Security-Guide version requirements.
       assert:
         that: "ansible_version.full is version_compare('2.5', '>=')"
         msg: >
           "You must update Ansible to at least version 2.5 to use this role."

   tasks:
    - name: Allow httpd_t (e.g nginx) to bind to port 9443
      command: semanage port -a -t http_port_t -p tcp 9443
      tags:
        - selinux
        - CB-27855

    - name: Allow httpd_t (e.g nginx) to connect to port 7070
      shell: | 
        semanage port -a -t http_port_t -p tcp 7070
        setsebool -P httpd_can_network_connect on
      tags:
        - selinux
        - CB-27855

    - name: Rebuild selinux policies
      command: semodule -B
      tags:
        - selinux
        - CB-27855
