#!/usr/bin/env bash

# /etc/init.d/disable-thp
# description: disable-thp
# processname: disable-thp

# chkconfig: 345 80 30
# description: disable-thp
# processname: sdisable-thp

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

case "$1" in
	start)
		for path in redhat_transparent_hugepage transparent_hugepage; do
  			for file in enabled defrag; do
    			if test -f /sys/kernel/mm/${path}/${file}; then
      				echo never > /sys/kernel/mm/${path}/${file}
    			fi
  			done
		done
	;;
	stop)
	;;
	restart)
	;;
	status)
	;;
esac