#!/bin/bash

: ${AZURE_STORAGE_ACCOUNTS?}
: ${TARGET_LOCATIONS?}

IFS=',' read -r -a AZURE_STORAGE_ACCOUNTS_LIST <<< "$AZURE_STORAGE_ACCOUNTS"
IFS=',' read -r -a TARGET_LOCATIONS_LIST <<< "$TARGET_LOCATIONS"
TARGET_AZURE_STORAGE_ACCOUNTS=""
for AZURE_STORAGE_ACCOUNT in "${AZURE_STORAGE_ACCOUNTS_LIST[@]}"; do
  for TARGET_ACCOUNT in "${TARGET_LOCATIONS_LIST[@]}"; do
    [ "$TRACE" == 1 ] && echo "Checking '$AZURE_STORAGE_ACCOUNT' to ' $TARGET_ACCOUNT*'"
    if [[ $AZURE_STORAGE_ACCOUNT == " $TARGET_ACCOUNT:"* ]]; then
      TARGET_AZURE_STORAGE_ACCOUNTS+="$AZURE_STORAGE_ACCOUNT,"
    fi
  done
done
TARGET_AZURE_STORAGE_ACCOUNTS=${TARGET_AZURE_STORAGE_ACCOUNTS%,}

echo $TARGET_AZURE_STORAGE_ACCOUNTS
